-- =============================================================================
-- PRIME-HRM baseline schema (migration 1 of 2)
-- Generated 2026-07-14 from the live production database
-- (Supabase project nuhirhfevxoonendpfsm), scoped to the tables the PRIME-HRM
-- app actually uses. Unrelated systems sharing that database (agriko_*, ccb_*,
-- ceedo_*, ddm_*, ...) and backup/duplicate junk tables are excluded.
--
-- Apply this as the FIRST migration of the new project, followed by
-- 0002_functions_and_cron.sql. See README.md in this folder for the data
-- migration plan and a list of quirks found in the old schema.
-- =============================================================================

create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;


-- ============================== Shared / platform ==============================

create table public.organizations (
  id bigint generated by default as identity not null,
  name text,
  created_at timestamp with time zone default now() not null,
  constraint organizations_pkey PRIMARY KEY (id)
);

create table public.users (
  id uuid not null,
  email text default ''::text,
  firstname text default ''::text,
  middlename text default ''::text,
  lastname text default ''::text,
  org_id bigint,
  fullname text,
  created_at timestamp with time zone default (now() AT TIME ZONE 'utc'::text),
  active boolean default false,
  constraint users_pkey PRIMARY KEY (id)
);

create table public.error_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  system text,
  transaction text,
  "table" text,
  data text,
  error text,
  constraint error_logs_pkey PRIMARY KEY (id)
);


-- ============================== Core & settings ==============================

create table public.hrm_users (
  id uuid not null,
  created_at timestamp with time zone default now() not null,
  firstname text,
  middlename text,
  lastname text,
  assignment text,
  status text,
  email text,
  position_id bigint,
  school_id bigint,
  office_id bigint,
  district_id bigint,
  salary_grade text default ''::text,
  salary_step text default ''::text,
  avatar_url text,
  org_id bigint,
  fts tsvector generated always as (to_tsvector('english'::regconfig, ((((firstname || ' '::text) || middlename) || ''::text) || lastname))) stored,
  joining_date date,
  date_of_last_promotion date,
  position_type text,
  birthday date,
  date_of_last_designation date,
  gender text,
  session_token text,
  item_id bigint,
  salary_id bigint,
  step_increment_leave_days real default '0'::real,
  date_of_next_step_increment date,
  signature_path text,
  constraint hrm_users_pkey PRIMARY KEY (id)
);

create table public.hrm_system_access (
  id bigint generated by default as identity not null,
  type text,
  user_id uuid,
  org_id bigint,
  constraint hrm_system_access_pkey PRIMARY KEY (id)
);

create table public.hrm_districts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  name text,
  org_id bigint,
  head_user_id uuid,
  constraint hrm_districts_pkey PRIMARY KEY (id)
);

create table public.hrm_offices (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  name text,
  org_id bigint,
  head_user_id uuid,
  constraint hrm_offices_pkey PRIMARY KEY (id)
);

create table public.hrm_schools (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  name text,
  district_id bigint,
  type text,
  org_id bigint,
  school_id text,
  school_class json,
  size text,
  head_user_id uuid,
  constraint hrm_schools_pkey PRIMARY KEY (id)
);

create table public.hrm_positions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  org_id bigint,
  name text,
  type text,
  salary_grade smallint,
  constraint hrm_positions_pkey PRIMARY KEY (id)
);

create table public.hrm_position_qualifications (
  id bigint generated by default as identity not null,
  name text,
  description text,
  position_id bigint,
  constraint hrm_position_qualifications_pkey PRIMARY KEY (id)
);

create table public.hrm_implementing_units (
  id bigint generated by default as identity not null,
  name text,
  org_id bigint,
  constraint hrm_implementing_units_pkey PRIMARY KEY (id)
);

create table public.hrm_salaries (
  id bigint generated by default as identity not null,
  grade bigint,
  step bigint,
  salary real,
  logs jsonb,
  previous text,
  tranche text,
  is_active text,
  remarks text,
  constraint hrm_salaries_pkey PRIMARY KEY (id)
);

create table public.hrm_school_years (
  id uuid default gen_random_uuid() not null,
  title text not null,
  start_date date not null,
  end_date date not null,
  is_active boolean default false,
  created_at timestamp with time zone default now(),
  constraint hrm_school_years_pkey PRIMARY KEY (id)
);

create table public.hrm_announcements (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  title text,
  description text,
  constraint hrm_announcements_pkey PRIMARY KEY (id)
);

create table public.hrm_notifications (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now(),
  message text,
  url text,
  type text,
  reference_id smallint,
  is_read boolean default false,
  reference_table character varying,
  user_id uuid,
  request_tracker_id bigint,
  cto_user_id bigint,
  service_credit_user_id bigint,
  registration_id bigint,
  promotion_id bigint,
  cto_id bigint,
  service_credit_id bigint,
  remarks_comment_id bigint,
  remark_id bigint,
  ranking_committee_id bigint,
  nosi_id bigint,
  ranking_evaluator_id bigint,
  constraint hrm_notifications_pkey PRIMARY KEY (id)
);

create table public.hrm_majors (
  id bigint generated by default as identity not null,
  title text,
  type text,
  constraint hrm_majors_pkey PRIMARY KEY (id)
);

create table public.hrm_subjects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  title text,
  category_level text,
  constraint hrm_subjects_pkey PRIMARY KEY (id)
);

create table public.hrm_coordinatorships (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  title text,
  constraint hrm_coordinatorships_pkey PRIMARY KEY (id)
);

create table public.hrm_registrations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  firstname text,
  middlename text,
  lastname text,
  assignment text,
  org_id bigint,
  status text,
  email text,
  position_id bigint,
  school_id bigint,
  office_id bigint,
  district_id bigint,
  password text,
  gender text,
  constraint hrm_registrations_pkey PRIMARY KEY (id)
);


-- ============================== Personnel & records ==============================

create table public.hrm_pds (
  user_id uuid not null,
  firstname text,
  middlename text,
  lastname text,
  ext text,
  birthday date,
  place_of_birth text,
  gender text,
  civil_status text,
  height text,
  weight text,
  blood_type text,
  citizenship text,
  telephone text,
  mobile_number text,
  residential_house_no text,
  residential_street text,
  residential_subdivision text,
  residential_barangay text,
  residential_city text,
  residential_province text,
  residential_zip text,
  permanent_house_no text,
  permanent_street text,
  permanent_subdivision text,
  permanent_barangay text,
  permanent_city text,
  permanent_province text,
  permanent_zip text,
  gsis_no text,
  pagibig_no text,
  philhealth_no text,
  sss_no text,
  tin_no text,
  agency_employee_no text,
  spouse_firstname text,
  spouse_middlename text,
  spouse_lastname text,
  spouse_ext text,
  spouse_occupation text,
  spouse_employer text,
  spouse_business_address text,
  spouse_business_telephone text,
  father_firstname text,
  father_middlename text,
  father_lastname text,
  father_ext text,
  mother_firstname text,
  mother_middlename text,
  mother_lastname text,
  children json,
  educational_background json,
  eligibility json,
  work_experience json,
  voluntary_work_experience json,
  trainings json,
  special_skills json,
  non_academic_distinctions json,
  membership_association json,
  "references" json,
  constraint hrm_pds_pkey PRIMARY KEY (user_id)
);

create table public.hrm_assignments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  hrm_user_id uuid,
  designation text,
  area_assigned text,
  type text,
  add_to_service_record boolean,
  org_id bigint,
  school_id bigint,
  office_id bigint,
  district_id bigint,
  position_id bigint,
  "from" date,
  "to" date,
  reference_code text,
  status text,
  constraint hrm_assignments_pkey PRIMARY KEY (id)
);

create table public.hrm_designations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  hrm_user_id uuid,
  designation text,
  area_assigned text,
  type text,
  add_to_service_record boolean,
  org_id bigint,
  school_id bigint,
  office_id bigint,
  district_id bigint,
  position_id bigint,
  "from" date,
  "to" date,
  reference_code text,
  add_to_leave_card boolean,
  status text,
  constraint hrm_designations_pkey PRIMARY KEY (id)
);

create table public.hrm_items (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  item_number text,
  position_id bigint,
  school_id bigint,
  user_id uuid,
  updated_by uuid,
  updated_at timestamp with time zone default CURRENT_TIMESTAMP,
  org_id bigint,
  salary_grade text,
  vice text,
  sex text,
  birthday date,
  eligibility text,
  date_of_last_promotion date,
  date_of_original_appointment date,
  authorized_annual_salary text,
  actual_annual_salary text,
  area_code text,
  status text,
  area_type text,
  level text,
  tin_no text,
  umid_no text,
  reason_for_removal text,
  vacancy_type text,
  implementing_unit_id bigint,
  track text,
  strand text,
  office_id bigint,
  assigned_to text default 'school'::text,
  constraint hrm_items_pkey PRIMARY KEY (id)
);

create table public.hrm_items_removed (
  id bigint generated by default as identity /* was serial; converted */ not null,
  item_id bigint not null,
  user_id uuid not null,
  reason text not null,
  removed_at timestamp with time zone default now(),
  removed_by uuid,
  org_id bigint not null,
  item_number text,
  position_id bigint,
  school_id bigint,
  office_id bigint,
  salary_grade text,
  date_of_original_appointment date,
  date_of_last_promotion date,
  created_at timestamp with time zone default now(),
  implementing_unit_id bigint,
  constraint hrm_items_removed_pkey PRIMARY KEY (id)
);

create table public.hrm_personnel_coordinatorships (
  id bigint generated by default as identity not null,
  user_id uuid,
  coordinatorship_id bigint,
  constraint hrm_personnel_coordinatorships_pkey PRIMARY KEY (id)
);

create table public.hrm_personnel_grade_levels (
  id bigint generated by default as identity not null,
  user_id uuid,
  grade_level text,
  constraint hrm_personnel_grade_levels_pkey PRIMARY KEY (id)
);

create table public.hrm_personnel_majors (
  id bigint generated by default as identity not null,
  user_id uuid,
  major_id bigint,
  constraint hrm_personnel_majors_pkey PRIMARY KEY (id)
);

create table public.hrm_personnel_subjects (
  id bigint generated by default as identity not null,
  user_id uuid,
  subject_id bigint,
  school_year_id uuid,
  constraint hrm_personnel_subjects_pkey PRIMARY KEY (id)
);

create table public.hrm_promotions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  user_id uuid,
  effectivity_date date,
  org_id bigint,
  status text,
  item_id bigint,
  constraint hrm_promotions_pkey PRIMARY KEY (id)
);

create table public.hrm_service_records (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  user_id uuid,
  org_id bigint,
  "from" text,
  "to" text,
  designation text,
  status text,
  salary text,
  station text,
  branch text,
  separation_date text,
  separation_cause text,
  remarks text,
  created_by uuid,
  assignment_id bigint,
  designation_id bigint,
  nosi_id bigint,
  nosa_id bigint,
  days_without_pay text,
  personnel_action text,
  constraint hrm_service_records_pkey PRIMARY KEY (id)
);

create table public.hrm_nosa (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  user_id uuid,
  as_of_date date,
  effective_date date,
  new_amount real,
  new_grade text,
  new_step text,
  date date,
  reason text,
  other_reason text,
  previous_grade text,
  previous_step text,
  previous_amount text,
  constraint hrm_nosa_pkey PRIMARY KEY (id)
);

create table public.hrm_nosi (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  user_id uuid,
  as_of_date date,
  effective_date date,
  new_amount real,
  new_grade text,
  new_step text,
  date date,
  reason text,
  other_reason text,
  previous_grade text,
  previous_step text,
  previous_amount text,
  constraint hrm_nosi_pkey PRIMARY KEY (id)
);


-- ============================== Request tracker ==============================

create table public.hrm_request_trackers (
  id bigint generated by default as identity not null,
  reference_code text,
  type text,
  created_at timestamp with time zone default (now() AT TIME ZONE 'utc'::text),
  created_by uuid,
  current_status text,
  date_received timestamp without time zone,
  receiver_id uuid,
  date_created date default now(),
  leave_type text,
  leave_from text,
  leave_days text,
  leave_location text,
  leave_abroad text,
  leave_hospitalization text,
  leave_illness text,
  leave_study_purpose text,
  leave_other_purpose text,
  leave_specify_location text,
  leave_women_illness text,
  leave_commutation text,
  current_tracker text,
  current_approver_id uuid,
  locator_slip_purpose text,
  locator_slip_type text,
  locator_slip_date text,
  locator_slip_time text,
  locator_slip_destination text,
  service_record_print_request_purpose text,
  pass_slip_type text,
  pass_slip_intended_time_departure text,
  pass_slip_intended_time_arrival text,
  pass_slip_fixed_time_from text,
  pass_slip_fixed_time_to text,
  pass_slip_purpose text,
  pass_slip_reason text,
  travel_type text,
  travel_purpose text,
  travel_host text,
  travel_from date,
  travel_to date,
  travel_destination text,
  travel_fund_source text,
  undertime_permit_reason text,
  undertime_permit_time text,
  leave_credit_use_sl text,
  leave_credit_use_vl text,
  leave_credit_use_sc text,
  leave_credit_use_maternity text,
  leave_credit_use_paternity text,
  leave_credit_use_rehab text,
  leave_credit_use_spl text,
  leave_credit_use_slbw text,
  leave_credit_use_soloparent text,
  leave_credit_use_study text,
  leave_credit_use_emergency text,
  leave_credit_use_vawc text,
  leave_credit_use_adoption text,
  leave_days_with_pay text,
  leave_days_without_pay text,
  recommended_by uuid,
  certified_by uuid,
  approved_by uuid,
  certification_as_of text,
  credits_used jsonb,
  leave_to text,
  date_recommeded date,
  date_approved date,
  travel_with text,
  leave_reason text,
  locator_slip_return_time text,
  pass_slip_date text,
  leave_others_specify text,
  travel_official_type text,
  leave_credit_use_wellness text,
  constraint hrm_request_trackers_pkey PRIMARY KEY (id)
);

create table public.hrm_tracker_flow (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default (now() AT TIME ZONE 'utc'::text) not null,
  tracker_id bigint,
  receiver_id uuid,
  user_id uuid,
  status text,
  constraint hrm_tracker_flow_pkey PRIMARY KEY (id)
);

create table public.hrm_tracker_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  tracker_flow_id bigint,
  user_id uuid,
  message text,
  constraint hrm_tracker_logs_pkey PRIMARY KEY (id)
);

create table public.hrm_tracker_followers (
  id bigint generated by default as identity not null,
  tracker_id bigint,
  user_id uuid,
  constraint hrm_tracker_followers_pkey PRIMARY KEY (id)
);

create table public.hrm_request_tracker_stickies (
  id bigint generated by default as identity not null,
  tracker_id bigint,
  note text,
  color character varying,
  created_at timestamp with time zone default now(),
  user_id uuid,
  constraint hrm_request_tracker_stickies_pkey PRIMARY KEY (id)
);

create table public.hrm_remarks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now(),
  tracker_id bigint,
  sender_id uuid,
  message text,
  is_private boolean,
  reply_type character varying default ''::character varying,
  files json,
  promotion_id bigint,
  applicant_id bigint,
  constraint hrm_remarks_pkey PRIMARY KEY (id)
);

create table public.hrm_remarks_comments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now(),
  remarks_id bigint,
  sender_id uuid,
  message text,
  constraint hrm_remarks_comments_pkey PRIMARY KEY (id)
);

create table public.hrm_global_remarks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now(),
  sender_id uuid,
  message text,
  promotion_id bigint,
  constraint hrm_global_remarks_pkey PRIMARY KEY (id)
);

create table public.hrm_leave_dates (
  id bigint generated by default as identity not null,
  tracker_id bigint,
  date date,
  is_paid boolean default true,
  constraint hrm_leave_dates_pkey PRIMARY KEY (id)
);

create table public.hrm_leave_coc (
  id bigint generated by default as identity not null,
  tracker_id bigint,
  use_coc text,
  user_cto_id bigint,
  constraint hrm_leave_coc_pkey PRIMARY KEY (id)
);


-- ============================== Leave, CTO & service credits ==============================

create table public.hrm_leave_credits (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  type text,
  credits double precision,
  date_of_next_reset date,
  date_of_next_increment date,
  user_id uuid,
  position_type text,
  gender text,
  constraint hrm_leave_credits_pkey PRIMARY KEY (id)
);

create table public.hrm_leave_cards (
  id bigint generated by default as identity not null,
  created_at date default now() not null,
  "from" date,
  "to" date,
  particulars text,
  remarks text,
  credits_used text,
  credits_earned text,
  balance text,
  absence_with_pay text,
  absence_without_pay text,
  transaction_type text,
  adjustment_date date default now(),
  type text,
  user_id uuid,
  updated_by uuid,
  tracker_id bigint,
  constraint hrm_leave_cards_pkey PRIMARY KEY (id)
);

create table public.hrm_ctos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  reference_code text,
  date_issued date,
  "from" date,
  "to" date,
  expiration date,
  hours text,
  days text,
  total_hours text,
  status text,
  particulars text,
  coc real,
  org_id bigint,
  is_holiday boolean,
  so_number text,
  constraint hrm_ctos_pkey PRIMARY KEY (id)
);

create table public.hrm_cto_users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  hrm_user_id uuid,
  cto_id bigint,
  is_approved boolean default false,
  reference_code text,
  coc real,
  expiration date,
  used_coc real default '0'::real,
  status text,
  remarks text,
  original_coc real,
  constraint hrm_cto_users_pkey PRIMARY KEY (id)
);

create table public.hrm_service_credits (
  id bigint generated by default as identity not null,
  reference_code character varying,
  date_issued date,
  "from" date,
  "to" date,
  hours character varying,
  days character varying,
  total_hours character varying,
  status text,
  particulars text,
  created_at timestamp with time zone default now() not null,
  service_credits character varying,
  org_id bigint,
  so_number text,
  constraint hrm_service_credits_pkey PRIMARY KEY (id)
);

create table public.hrm_service_credit_users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  hrm_user_id uuid,
  service_credit_id bigint,
  is_approved boolean default false,
  reference_code character varying,
  service_credits real,
  used_service_credits real default '0'::real,
  remarks text,
  constraint hrm_service_credit_users_pkey PRIMARY KEY (id)
);


-- ============================== Ranking & selection (RSP) ==============================

create table public.hrm_ranking_applicant_documents (
  id bigint generated by default as identity not null,
  applicant_id bigint,
  qualification_id bigint,
  document_url text,
  created_at timestamp with time zone default now(),
  status text default 'For Evaluation'::text,
  remarks text default ''::text,
  constraint hrm_ranking_applicant_documents_pkey PRIMARY KEY (id)
);

create table public.hrm_ranking_applicant_flow (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default (now() AT TIME ZONE 'utc'::text) not null,
  receiver_id uuid,
  user_id uuid,
  status text,
  applicant_id bigint,
  constraint hrm_ranking_applicant_flow_pkey PRIMARY KEY (id)
);

create table public.hrm_ranking_applicant_ier (
  id bigint generated by default as identity not null,
  applicant_id bigint,
  qualification_id bigint,
  created_at timestamp with time zone default now(),
  remarks text default ''::text,
  time text,
  type text,
  status text,
  constraint hrm_ranking_applicant_ier_pkey PRIMARY KEY (id)
);

create table public.hrm_ranking_applicant_points (
  applicant_id bigint,
  committee_criteria_id bigint not null,
  points text,
  id bigint generated by default as identity not null,
  constraint hrm_ranking_applicant_points_pkey PRIMARY KEY (id)
);

create table public.hrm_ranking_applicants (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  type text,
  ranking_id bigint,
  lastname text,
  firstname text,
  middlename text,
  code text,
  email text,
  deped_email text,
  current_employee text,
  previous_applicant text,
  previous_applicant_code text,
  user_id uuid,
  status text default 'Active'::text,
  address text,
  age text,
  civil_status text,
  religion text,
  disability text,
  ethnicity text,
  ethnicity_detail text,
  solo_parent text,
  solo_parent_detail text,
  contact_number text,
  specific_major text,
  sex text,
  professional_study text,
  professional_study_file_path text,
  professional_study_units text,
  teaching_public_school text,
  teaching_public_school_file_path text,
  teaching_public_school_units text,
  teaching_private_school text,
  teaching_private_school_file_path text,
  teaching_private_school_units text,
  supervisory_public_school text,
  supervisory_public_school_file_path text,
  supervisory_public_school_units text,
  supervisory_private_school text,
  supervisory_private_school_file_path text,
  supervisory_private_school_units text,
  seminars text,
  seminars_file_path text,
  seminars_units text,
  current_approver_id uuid,
  office_id bigint,
  school_id bigint,
  latin_honor text,
  special_program_beneficiary text,
  special_skills text,
  email_sent boolean default false,
  evaluation_status text default 'For Evaluation'::text,
  reason_for_disqualification text,
  eir_email_sent boolean default false,
  ies_email_sent boolean default false,
  item_id bigint,
  constraint hrm_ranking_applicants_pkey PRIMARY KEY (id)
);

create table public.hrm_ranking_committee_criterias (
  id bigint generated by default as identity not null,
  committee_id bigint,
  criteria_id bigint,
  constraint hrm_ranking_committee_criterias_pkey PRIMARY KEY (id)
);

create table public.hrm_ranking_committees (
  id bigint generated by default as identity not null,
  user_id uuid,
  type text,
  ranking_id bigint,
  status text default 'Pending Confirmation'::text,
  constraint hrm_ranking_committees_pkey PRIMARY KEY (id)
);

create table public.hrm_ranking_criterias (
  id bigint generated by default as identity not null,
  name text,
  points text,
  ranking_id bigint,
  type text,
  potential text,
  constraint hrm_ranking_criterias_pkey PRIMARY KEY (id)
);

create table public.hrm_ranking_evaluators (
  id bigint generated by default as identity not null,
  user_id uuid,
  ranking_id bigint,
  constraint hrm_ranking_evaluators_pkey PRIMARY KEY (id)
);

create table public.hrm_ranking_expenses_summary (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  particulars text,
  total_applicants text,
  unit_cost text,
  time_spent_per_applicant text,
  amount text,
  ranking_id bigint,
  constraint hrm_ranking_expenses_summary_pkey PRIMARY KEY (id)
);

create table public.hrm_ranking_qualifications (
  id bigint generated by default as identity not null,
  ranking_id bigint,
  name text,
  description text,
  required boolean default false,
  constraint hrm_ranking_qualifications_pkey PRIMARY KEY (id)
);

create table public.hrm_rankings (
  id bigint generated by default as identity not null,
  type text,
  position_id bigint,
  chairman_id uuid,
  department text,
  description text,
  status text default ''::text,
  display_on_portal_until date,
  org_id bigint,
  year text,
  days_to_comply date,
  display_on_portal_from date,
  display_ier boolean default false,
  display_on_portal boolean default false,
  passing_score text,
  display_rqa boolean default false,
  display_ranklist boolean default false,
  display_nai boolean default false,
  code_prefix text,
  ier_education_description text,
  ier_eligibility_description text,
  ier_experience_description text,
  ier_training_description text,
  created_at timestamp with time zone default now(),
  constraint hrm_rankings_pkey PRIMARY KEY (id)
);

create table public.hrm_erf_applicants (
  id bigint generated by default as identity not null,
  reference_code text,
  type text,
  created_at timestamp with time zone default (now() AT TIME ZONE 'utc'::text),
  created_by uuid,
  current_status text,
  date_received timestamp without time zone,
  receiver_id uuid,
  date_created date default now(),
  current_tracker text,
  current_approver_id uuid,
  constraint hrm_erf_applicants_pkey PRIMARY KEY (id)
);


-- ============================== Annual physical exams ==============================

create table public.hrm_annual_physical_exams (
  id uuid default gen_random_uuid() not null,
  org_id text not null,
  hrm_user_id uuid not null,
  exam_date date not null,
  remarks text,
  fitness_result text,
  diagnosis text,
  diagnosed_by uuid,
  diagnosed_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  medical_history jsonb,
  medical_officer_remarks text,
  constraint hrm_annual_physical_exams_pkey PRIMARY KEY (id)
);

create table public.hrm_ape_diagnoses (
  id uuid default gen_random_uuid() not null,
  org_id text not null,
  ape_id uuid not null,
  diagnosis text not null,
  diagnosis_date date default CURRENT_DATE not null,
  diagnosed_by uuid,
  created_at timestamp with time zone default now() not null,
  constraint hrm_ape_diagnoses_pkey PRIMARY KEY (id)
);

create table public.hrm_medical_officers (
  id uuid default gen_random_uuid() not null,
  org_id text not null,
  user_id uuid not null,
  created_at timestamp with time zone default now() not null,
  constraint hrm_medical_officers_pkey PRIMARY KEY (id)
);

create table public.hrm_medical_officer_schools (
  id uuid default gen_random_uuid() not null,
  org_id text not null,
  medical_officer_id uuid not null,
  school_id bigint not null,
  created_at timestamp with time zone default now() not null,
  constraint hrm_medical_officer_schools_pkey PRIMARY KEY (id)
);


-- ============================== Learning & development ==============================

create table public.hrm_interventions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  title text,
  constraint hrm_interventions_pkey PRIMARY KEY (id)
);

create table public.hrm_development_plans (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  user_id uuid,
  strength_objective_id bigint,
  weak_objective_id bigint,
  intervention_id bigint,
  learning_objectives text,
  timeline text,
  resources_needed text,
  system_type text default '''System Generated'''::text,
  type text,
  ipcrf_id bigint,
  strength_competency_id bigint,
  weak_competency_id bigint,
  constraint hrm_development_plans_pkey PRIMARY KEY (id)
);


-- ============================== Performance management (PMS) ==============================

create table public.kra (
  id bigint generated by default as identity not null,
  title text,
  is_archive character varying default ''::character varying,
  constraint kra_pkey PRIMARY KEY (id)
);

create table public.kra_objectives (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now(),
  kra_id bigint not null,
  title text,
  has_efficiency character varying default ''::character varying,
  has_timeliness character varying default ''::character varying,
  mov text,
  is_archive character varying default ''::character varying,
  constraint kra_objectives_pkey PRIMARY KEY (id)
);

create table public.ipcrfs (
  id bigint generated by default as identity not null,
  user_id uuid,
  ipcrf_template_id uuid,
  rater_user_id uuid,
  created_at timestamp with time zone default now(),
  objectives jsonb,
  competencies jsonb,
  score character varying,
  adjectival_rating character varying,
  status character varying default 'Pending Approval'::character varying,
  development_plans jsonb,
  constraint ipcrfs_pkey PRIMARY KEY (id)
);

create table public.ipcrf_templates (
  id uuid default uuid_generate_v4() not null,
  title text,
  created_at timestamp with time zone default now(),
  positions jsonb,
  objectives jsonb,
  competencies jsonb,
  is_archive boolean default false,
  is_published boolean default false,
  constraint ipcrf_templates_pkey PRIMARY KEY (id)
);

create table public.competencies (
  id bigint generated by default as identity not null,
  title text,
  is_archive character varying default ''::character varying,
  type character varying,
  item_1 text,
  item_2 text,
  item_3 text,
  item_4 text,
  item_5 text,
  created_at timestamp without time zone default now(),
  constraint competencies_pkey PRIMARY KEY (id)
);

create table public.competency_items (
  id bigint generated by default as identity not null,
  title text,
  created_at timestamp with time zone default now(),
  competency_id bigint,
  constraint competency_items_pkey PRIMARY KEY (id)
);

create table public.chiefs_opcrf (
  id uuid default uuid_generate_v4() not null,
  title text,
  is_archive character varying default ''::character varying,
  created_at timestamp with time zone default now(),
  positions jsonb,
  objectives jsonb,
  is_published character varying default ''::character varying,
  score character varying,
  adjectival_rating character varying,
  user_id uuid,
  status character varying default 'Pending Approval'::character varying,
  development_plans jsonb,
  constraint chiefs_opcrf_pkey PRIMARY KEY (id)
);

create table public.pms_competencies (
  id bigint generated by default as identity not null,
  title text,
  type text,
  constraint pms_competencies_pkey PRIMARY KEY (id)
);

create table public.pms_competency_items (
  id bigint generated by default as identity not null,
  competency_id bigint,
  title text,
  constraint pms_competency_items_pkey PRIMARY KEY (id)
);

create table public.pms_idp (
  id bigint generated by default as identity not null,
  ipcrf_id bigint not null,
  learning_objective text,
  intervention text,
  timeline text,
  resources text,
  created_at timestamp without time zone default now(),
  type text,
  comp_type text,
  is_custom_objective boolean default false,
  is_custom_competency boolean default false,
  is_custom_intervention boolean default false,
  custom_objective text,
  custom_competency text,
  custom_intervention text,
  objective_id bigint,
  competency_item_id bigint,
  constraint pms_idp_pkey PRIMARY KEY (id)
);

create table public.pms_ipcrf (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  ipcrf_template_id bigint,
  user_id uuid,
  rater_id uuid,
  description text,
  type text,
  constraint pms_ipcrf_pkey PRIMARY KEY (id)
);

create table public.pms_ipcrf_competency_ratings (
  id bigint generated by default as identity not null,
  ipcrf_id bigint not null,
  competency_item_id bigint not null,
  period text not null,
  rater_type text not null,
  created_at timestamp without time zone default now(),
  constraint pms_ipcrf_competency_ratings_pkey PRIMARY KEY (id)
);

create table public.pms_ipcrf_objective_ratings (
  id bigint generated by default as identity not null,
  ipcrf_id bigint not null,
  template_objective_id bigint not null,
  period text not null,
  rater_type text not null,
  quality integer,
  efficiency integer,
  timeliness integer,
  constraint pms_ipcrf_objective_ratings_pkey PRIMARY KEY (id)
);

create table public.pms_ipcrf_positions (
  id bigint generated by default as identity not null,
  position_id bigint,
  ipcrf_template_id bigint,
  constraint pms_ipcrf_positions_pkey PRIMARY KEY (id)
);

create table public.pms_ipcrf_template_competencies (
  id bigint generated by default as identity not null,
  competency_id bigint,
  ipcrf_template_id bigint,
  constraint pms_ipcrf_template_competencies_pkey PRIMARY KEY (id)
);

create table public.pms_ipcrf_template_objectives (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  ipcrf_template_id bigint,
  timeline text,
  weight numeric,
  target text,
  quality boolean,
  efficiency boolean,
  timeliness boolean,
  quality_outstanding text,
  quality_very_satisfactory text,
  quality_satisfactory text,
  quality_unsatisfactory text,
  quality_poor text,
  objective_id bigint,
  efficiency_outstanding text,
  efficiency_very_satisfactory text,
  efficiency_satisfactory text,
  efficiency_unsatisfactory text,
  efficiency_poor text,
  timeliness_outstanding text,
  timeliness_very_satisfactory text,
  timeliness_satisfactory text,
  timeliness_unsatisfactory text,
  timeliness_poor text,
  constraint pms_ipcrf_template_objectives_pkey PRIMARY KEY (id)
);

create table public.pms_ipcrf_templates (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  description text,
  status text default 'Disabled'::text,
  created_by uuid,
  type text,
  constraint pms_ipcrf_templates_pkey PRIMARY KEY (id)
);

create table public.pms_kras (
  id bigint generated by default as identity not null,
  title text,
  constraint pms_kras_pkey PRIMARY KEY (id)
);

create table public.pms_objectives (
  id bigint generated by default as identity not null,
  kra_id bigint,
  title text,
  constraint pms_objectives_pkey PRIMARY KEY (id)
);


-- ============================== Rewards & recognition (R&R) ==============================

create table public.rr_candidates (
  id bigint generated always as identity not null,
  ranking_id bigint,
  employee_id uuid,
  created_at timestamp with time zone default now(),
  constraint rr_candidates_pkey PRIMARY KEY (id)
);

create table public.rr_criteria (
  id bigint generated always as identity not null,
  ranking_id bigint,
  name text not null,
  description text,
  weight integer not null,
  created_at timestamp with time zone default now(),
  constraint rr_criteria_pkey PRIMARY KEY (id)
);

create table public.rr_rankings (
  id bigint generated always as identity not null,
  title text not null,
  description text,
  created_at timestamp with time zone default now(),
  constraint rr_rankings_pkey PRIMARY KEY (id)
);

create table public.rr_raters (
  id bigint generated by default as identity not null,
  rater_id uuid,
  created_at timestamp with time zone default now(),
  ranking_id bigint,
  constraint rr_raters_pkey PRIMARY KEY (id)
);

create table public.rr_ratings (
  id bigint generated always as identity not null,
  rater_id bigint,
  ranking_id bigint,
  candidate_id bigint,
  criterion_id bigint,
  points integer not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint rr_ratings_pkey PRIMARY KEY (id)
);


-- ============================== Foreign keys ==============================

alter table public.chiefs_opcrf add constraint chiefs_opcrf_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
alter table public.competency_items add constraint competency_items_competency_id_fkey FOREIGN KEY (competency_id) REFERENCES competencies(id) ON DELETE CASCADE;
alter table public.hrm_annual_physical_exams add constraint hrm_annual_physical_exams_diagnosed_by_fkey FOREIGN KEY (diagnosed_by) REFERENCES hrm_users(id);
alter table public.hrm_annual_physical_exams add constraint hrm_annual_physical_exams_hrm_user_id_fkey FOREIGN KEY (hrm_user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_ape_diagnoses add constraint hrm_ape_diagnoses_ape_id_fkey FOREIGN KEY (ape_id) REFERENCES hrm_annual_physical_exams(id) ON DELETE CASCADE;
alter table public.hrm_ape_diagnoses add constraint hrm_ape_diagnoses_diagnosed_by_fkey FOREIGN KEY (diagnosed_by) REFERENCES hrm_users(id);
alter table public.hrm_assignments add constraint hrm_assignments_district_id_fkey FOREIGN KEY (district_id) REFERENCES hrm_districts(id) ON DELETE SET NULL;
alter table public.hrm_assignments add constraint hrm_assignments_hrm_user_id_fkey FOREIGN KEY (hrm_user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_assignments add constraint hrm_assignments_office_id_fkey FOREIGN KEY (office_id) REFERENCES hrm_offices(id) ON DELETE SET NULL;
alter table public.hrm_assignments add constraint hrm_assignments_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_assignments add constraint hrm_assignments_position_id_fkey FOREIGN KEY (position_id) REFERENCES hrm_positions(id) ON DELETE SET NULL;
alter table public.hrm_assignments add constraint hrm_assignments_school_id_fkey FOREIGN KEY (school_id) REFERENCES hrm_schools(id) ON DELETE SET NULL;
alter table public.hrm_cto_users add constraint hrm_cto_users_cto_id_fkey FOREIGN KEY (cto_id) REFERENCES hrm_ctos(id) ON DELETE CASCADE;
alter table public.hrm_cto_users add constraint hrm_cto_users_hrm_user_id_fkey FOREIGN KEY (hrm_user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_ctos add constraint hrm_ctos_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_designations add constraint hrm_designations_district_id_fkey FOREIGN KEY (district_id) REFERENCES hrm_districts(id) ON DELETE SET NULL;
alter table public.hrm_designations add constraint hrm_designations_hrm_user_id_fkey FOREIGN KEY (hrm_user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_designations add constraint hrm_designations_office_id_fkey FOREIGN KEY (office_id) REFERENCES hrm_offices(id) ON DELETE SET NULL;
alter table public.hrm_designations add constraint hrm_designations_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_designations add constraint hrm_designations_position_id_fkey FOREIGN KEY (position_id) REFERENCES hrm_positions(id) ON DELETE SET NULL;
alter table public.hrm_designations add constraint hrm_designations_school_id_fkey FOREIGN KEY (school_id) REFERENCES hrm_schools(id) ON DELETE SET NULL;
alter table public.hrm_development_plans add constraint hrm_development_plans_intervention_id_fkey FOREIGN KEY (intervention_id) REFERENCES hrm_interventions(id) ON DELETE CASCADE;
alter table public.hrm_development_plans add constraint hrm_development_plans_ipcrf_id_fkey FOREIGN KEY (ipcrf_id) REFERENCES ipcrfs(id) ON DELETE CASCADE;
alter table public.hrm_development_plans add constraint hrm_development_plans_strength_competency_id_fkey FOREIGN KEY (strength_competency_id) REFERENCES competencies(id) ON DELETE CASCADE;
alter table public.hrm_development_plans add constraint hrm_development_plans_strength_objective_id_fkey FOREIGN KEY (strength_objective_id) REFERENCES kra_objectives(id) ON DELETE CASCADE;
alter table public.hrm_development_plans add constraint hrm_development_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_development_plans add constraint hrm_development_plans_weak_competency_id_fkey FOREIGN KEY (weak_competency_id) REFERENCES competencies(id) ON DELETE CASCADE;
alter table public.hrm_development_plans add constraint hrm_development_plans_weak_objective_id_fkey FOREIGN KEY (weak_objective_id) REFERENCES kra_objectives(id) ON DELETE CASCADE;
alter table public.hrm_districts add constraint hrm_districts_head_user_id_fkey FOREIGN KEY (head_user_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_districts add constraint hrm_districts_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_erf_applicants add constraint hrm_erf_screening_created_by_fkey FOREIGN KEY (created_by) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_erf_applicants add constraint hrm_erf_screening_current_approver_id_fkey FOREIGN KEY (current_approver_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_erf_applicants add constraint hrm_erf_screening_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_global_remarks add constraint hrm_global_remarks_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES hrm_promotions(id) ON DELETE CASCADE;
alter table public.hrm_global_remarks add constraint hrm_global_remarks_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_implementing_units add constraint hrm_implementing_units_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_items add constraint hrm_items_duplicate_implementing_unit_id_fkey FOREIGN KEY (implementing_unit_id) REFERENCES hrm_implementing_units(id) ON DELETE SET NULL;
alter table public.hrm_items add constraint hrm_items_duplicate_office_id_fkey FOREIGN KEY (office_id) REFERENCES hrm_offices(id) ON DELETE SET NULL;
alter table public.hrm_items add constraint hrm_items_duplicate_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_items add constraint hrm_items_duplicate_position_id_fkey FOREIGN KEY (position_id) REFERENCES hrm_positions(id) ON DELETE SET NULL;
alter table public.hrm_items add constraint hrm_items_duplicate_school_id_fkey FOREIGN KEY (school_id) REFERENCES hrm_schools(id) ON DELETE SET NULL;
alter table public.hrm_items add constraint hrm_items_duplicate_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_items add constraint hrm_items_duplicate_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_items_removed add constraint hrm_items_removed_implementing_unit_id_fkey FOREIGN KEY (implementing_unit_id) REFERENCES hrm_implementing_units(id) ON DELETE SET NULL;
alter table public.hrm_items_removed add constraint hrm_items_removed_item_id_fkey FOREIGN KEY (item_id) REFERENCES hrm_items(id) ON DELETE CASCADE;
alter table public.hrm_items_removed add constraint hrm_items_removed_office_id_fkey FOREIGN KEY (office_id) REFERENCES hrm_offices(id);
alter table public.hrm_items_removed add constraint hrm_items_removed_position_id_fkey FOREIGN KEY (position_id) REFERENCES hrm_positions(id);
alter table public.hrm_items_removed add constraint hrm_items_removed_removed_by_fkey FOREIGN KEY (removed_by) REFERENCES hrm_users(id);
alter table public.hrm_items_removed add constraint hrm_items_removed_school_id_fkey FOREIGN KEY (school_id) REFERENCES hrm_schools(id);
alter table public.hrm_items_removed add constraint hrm_items_removed_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_leave_cards add constraint hrm_leave_cards_tracker_id_fkey1 FOREIGN KEY (tracker_id) REFERENCES hrm_request_trackers(id) ON DELETE CASCADE;
alter table public.hrm_leave_cards add constraint hrm_leave_cards_updated_by_fkey1 FOREIGN KEY (updated_by) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_leave_cards add constraint hrm_leave_cards_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_leave_coc add constraint hrm_leave_coc_tracker_id_fkey FOREIGN KEY (tracker_id) REFERENCES hrm_request_trackers(id) ON DELETE CASCADE;
alter table public.hrm_leave_coc add constraint hrm_leave_coc_user_cto_id_fkey FOREIGN KEY (user_cto_id) REFERENCES hrm_cto_users(id) ON DELETE CASCADE;
alter table public.hrm_leave_credits add constraint hrm_leave_credits_duplicate_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_leave_dates add constraint hrm_leave_dates_tracker_id_fkey FOREIGN KEY (tracker_id) REFERENCES hrm_request_trackers(id) ON DELETE CASCADE;
alter table public.hrm_medical_officer_schools add constraint hrm_medical_officer_schools_medical_officer_id_fkey FOREIGN KEY (medical_officer_id) REFERENCES hrm_medical_officers(id) ON DELETE CASCADE;
alter table public.hrm_medical_officer_schools add constraint hrm_medical_officer_schools_school_id_fkey FOREIGN KEY (school_id) REFERENCES hrm_schools(id) ON DELETE CASCADE;
alter table public.hrm_medical_officers add constraint hrm_medical_officers_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_nosa add constraint hrm_nosi_duplicate_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_nosi add constraint hrm_nosi_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_notifications add constraint hrm_notifications_cto_id_fkey FOREIGN KEY (cto_id) REFERENCES hrm_ctos(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_cto_user_id_fkey FOREIGN KEY (cto_user_id) REFERENCES hrm_cto_users(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_nosi_id_fkey FOREIGN KEY (nosi_id) REFERENCES hrm_nosi(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES hrm_promotions(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_ranking_committee_id_fkey FOREIGN KEY (ranking_committee_id) REFERENCES hrm_ranking_committees(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_ranking_evaluator_id_fkey FOREIGN KEY (ranking_evaluator_id) REFERENCES hrm_ranking_evaluators(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES hrm_registrations(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_remark_id_fkey FOREIGN KEY (remark_id) REFERENCES hrm_remarks(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_remarks_comment_id_fkey FOREIGN KEY (remarks_comment_id) REFERENCES hrm_remarks_comments(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_request_tracker_id_fkey FOREIGN KEY (request_tracker_id) REFERENCES hrm_request_trackers(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_service_credit_id_fkey FOREIGN KEY (service_credit_id) REFERENCES hrm_service_credits(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_service_credit_user_id_fkey FOREIGN KEY (service_credit_user_id) REFERENCES hrm_service_credit_users(id) ON DELETE CASCADE;
alter table public.hrm_notifications add constraint hrm_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_offices add constraint hrm_offices_head_user_id_fkey FOREIGN KEY (head_user_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_offices add constraint hrm_offices_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_pds add constraint hrm_pds_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_personnel_coordinatorships add constraint hrm_personnel_coordinatorships_coordinatorship_id_fkey FOREIGN KEY (coordinatorship_id) REFERENCES hrm_coordinatorships(id) ON DELETE CASCADE;
alter table public.hrm_personnel_coordinatorships add constraint hrm_personnel_coordinatorships_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_personnel_grade_levels add constraint hrm_personnel_grade_levels_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_personnel_majors add constraint hrm_personnel_majors_major_id_fkey FOREIGN KEY (major_id) REFERENCES hrm_majors(id) ON DELETE CASCADE;
alter table public.hrm_personnel_majors add constraint hrm_personnel_majors_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_personnel_subjects add constraint hrm_personnel_subjects_school_year_id_fkey FOREIGN KEY (school_year_id) REFERENCES hrm_school_years(id) ON DELETE SET NULL;
alter table public.hrm_personnel_subjects add constraint hrm_personnel_subjects_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES hrm_subjects(id) ON DELETE CASCADE;
alter table public.hrm_personnel_subjects add constraint hrm_personnel_subjects_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_position_qualifications add constraint hrm_position_qualifications_position_id_fkey FOREIGN KEY (position_id) REFERENCES hrm_positions(id) ON DELETE CASCADE;
alter table public.hrm_positions add constraint hrm_positions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_promotions add constraint hrm_promotions_item_id_fkey FOREIGN KEY (item_id) REFERENCES hrm_items(id) ON DELETE SET NULL;
alter table public.hrm_promotions add constraint hrm_promotions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_promotions add constraint hrm_promotions_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicant_documents add constraint hrm_ranking_applicant_documents_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES hrm_ranking_applicants(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicant_documents add constraint hrm_ranking_applicant_documents_qualification_id_fkey FOREIGN KEY (qualification_id) REFERENCES hrm_ranking_qualifications(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicant_flow add constraint hrm_ranking_applicant_flow_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES hrm_ranking_applicants(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicant_flow add constraint hrm_ranking_applicant_flow_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicant_flow add constraint hrm_ranking_applicant_flow_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicant_ier add constraint hrm_ranking_applicant_ier_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES hrm_ranking_applicants(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicant_ier add constraint hrm_ranking_applicant_ier_qualification_id_fkey FOREIGN KEY (qualification_id) REFERENCES hrm_ranking_qualifications(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicant_points add constraint hrm_applicant_points_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES hrm_ranking_applicants(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicant_points add constraint hrm_applicant_points_committee_criteria_id_fkey FOREIGN KEY (committee_criteria_id) REFERENCES hrm_ranking_committee_criterias(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicants add constraint hrm_applications_ranking_id_fkey FOREIGN KEY (ranking_id) REFERENCES hrm_rankings(id) ON DELETE SET NULL;
alter table public.hrm_ranking_applicants add constraint hrm_ranking_applicants_current_approver_id_fkey FOREIGN KEY (current_approver_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_ranking_applicants add constraint hrm_ranking_applicants_item_id_fkey FOREIGN KEY (item_id) REFERENCES hrm_items(id) ON DELETE SET NULL;
alter table public.hrm_ranking_applicants add constraint hrm_ranking_applicants_office_id_fkey FOREIGN KEY (office_id) REFERENCES hrm_offices(id) ON DELETE SET NULL;
alter table public.hrm_ranking_applicants add constraint hrm_ranking_applicants_school_id_fkey FOREIGN KEY (school_id) REFERENCES hrm_schools(id) ON DELETE SET NULL;
alter table public.hrm_ranking_applicants add constraint hrm_ranking_applicants_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_ranking_committee_criterias add constraint hrm_ranking_committee_criterias_committee_id_fkey FOREIGN KEY (committee_id) REFERENCES hrm_ranking_committees(id) ON DELETE CASCADE;
alter table public.hrm_ranking_committee_criterias add constraint hrm_ranking_committee_criterias_criteria_id_fkey FOREIGN KEY (criteria_id) REFERENCES hrm_ranking_criterias(id) ON DELETE CASCADE;
alter table public.hrm_ranking_committees add constraint hrm_ranking_committees_ranking_id_fkey FOREIGN KEY (ranking_id) REFERENCES hrm_rankings(id) ON DELETE CASCADE;
alter table public.hrm_ranking_committees add constraint hrm_ranking_committees_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_ranking_criterias add constraint hrm_ranking_criterias_ranking_id_fkey FOREIGN KEY (ranking_id) REFERENCES hrm_rankings(id) ON DELETE CASCADE;
alter table public.hrm_ranking_evaluators add constraint hrm_ranking_evaluators_ranking_id_fkey FOREIGN KEY (ranking_id) REFERENCES hrm_rankings(id) ON DELETE CASCADE;
alter table public.hrm_ranking_evaluators add constraint hrm_ranking_evaluators_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_ranking_expenses_summary add constraint hrm_ranking_expenses_summary_ranking_id_fkey FOREIGN KEY (ranking_id) REFERENCES hrm_rankings(id) ON DELETE CASCADE;
alter table public.hrm_ranking_qualifications add constraint hrm_ranking_qualifications_ranking_id_fkey FOREIGN KEY (ranking_id) REFERENCES hrm_rankings(id) ON DELETE CASCADE;
alter table public.hrm_rankings add constraint hrm_rankings_chairman_id_fkey FOREIGN KEY (chairman_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_rankings add constraint hrm_rankings_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_rankings add constraint hrm_rankings_position_id_fkey FOREIGN KEY (position_id) REFERENCES hrm_positions(id) ON DELETE SET NULL;
alter table public.hrm_registrations add constraint hrm_registrations_district_id_fkey FOREIGN KEY (district_id) REFERENCES hrm_districts(id) ON DELETE SET NULL;
alter table public.hrm_registrations add constraint hrm_registrations_office_id_fkey FOREIGN KEY (office_id) REFERENCES hrm_offices(id) ON DELETE SET NULL;
alter table public.hrm_registrations add constraint hrm_registrations_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_registrations add constraint hrm_registrations_position_id_fkey FOREIGN KEY (position_id) REFERENCES hrm_positions(id) ON DELETE SET NULL;
alter table public.hrm_registrations add constraint hrm_registrations_school_id_fkey FOREIGN KEY (school_id) REFERENCES hrm_schools(id) ON DELETE SET NULL;
alter table public.hrm_remarks add constraint hrm_remarks_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES hrm_ranking_applicants(id) ON DELETE CASCADE;
alter table public.hrm_remarks add constraint hrm_remarks_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES hrm_promotions(id) ON DELETE CASCADE;
alter table public.hrm_remarks add constraint hrm_remarks_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_remarks add constraint hrm_remarks_tracker_id_fkey FOREIGN KEY (tracker_id) REFERENCES hrm_request_trackers(id) ON DELETE CASCADE;
alter table public.hrm_remarks_comments add constraint hrm_remarks_comments_remarks_id_fkey FOREIGN KEY (remarks_id) REFERENCES hrm_remarks(id) ON DELETE CASCADE;
alter table public.hrm_remarks_comments add constraint hrm_remarks_comments_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_request_tracker_stickies add constraint hrm_request_tracker_stickies_tracker_id_fkey FOREIGN KEY (tracker_id) REFERENCES hrm_request_trackers(id) ON DELETE CASCADE;
alter table public.hrm_request_tracker_stickies add constraint hrm_request_tracker_stickies_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_request_trackers add constraint hrm_request_trackers_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_request_trackers add constraint hrm_request_trackers_certified_by_fkey FOREIGN KEY (certified_by) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_request_trackers add constraint hrm_request_trackers_created_by_fkey FOREIGN KEY (created_by) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_request_trackers add constraint hrm_request_trackers_current_approver_id_fkey FOREIGN KEY (current_approver_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_request_trackers add constraint hrm_request_trackers_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_request_trackers add constraint hrm_request_trackers_recommended_by_fkey FOREIGN KEY (recommended_by) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_schools add constraint hrm_schools_district_id_fkey FOREIGN KEY (district_id) REFERENCES hrm_districts(id) ON DELETE SET NULL;
alter table public.hrm_schools add constraint hrm_schools_head_user_id_fkey FOREIGN KEY (head_user_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_schools add constraint hrm_schools_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.hrm_service_credit_users add constraint hrm_service_credit_users_hrm_user_id_fkey FOREIGN KEY (hrm_user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_service_credit_users add constraint hrm_service_credit_users_service_credit_id_fkey FOREIGN KEY (service_credit_id) REFERENCES hrm_service_credits(id) ON DELETE CASCADE;
alter table public.hrm_service_credits add constraint hrm_service_credits_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id);
alter table public.hrm_service_records add constraint hrm_service_records_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES hrm_assignments(id) ON DELETE CASCADE;
alter table public.hrm_service_records add constraint hrm_service_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_service_records add constraint hrm_service_records_designation_id_fkey FOREIGN KEY (designation_id) REFERENCES hrm_designations(id) ON DELETE CASCADE;
alter table public.hrm_service_records add constraint hrm_service_records_nosa_id_fkey FOREIGN KEY (nosa_id) REFERENCES hrm_nosa(id) ON DELETE CASCADE;
alter table public.hrm_service_records add constraint hrm_service_records_nosi_id_fkey FOREIGN KEY (nosi_id) REFERENCES hrm_nosi(id) ON DELETE CASCADE;
alter table public.hrm_service_records add constraint hrm_service_records_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_service_records add constraint hrm_service_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.hrm_system_access add constraint hrm_system_access_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.hrm_system_access add constraint hrm_system_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_tracker_flow add constraint hrm_tracker_flow_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_tracker_flow add constraint hrm_tracker_flow_tracker_id_fkey FOREIGN KEY (tracker_id) REFERENCES hrm_request_trackers(id) ON DELETE CASCADE;
alter table public.hrm_tracker_flow add constraint hrm_tracker_flow_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_tracker_followers add constraint hrm_tracker_followers_tracker_id_fkey FOREIGN KEY (tracker_id) REFERENCES hrm_request_trackers(id) ON DELETE CASCADE;
alter table public.hrm_tracker_followers add constraint hrm_tracker_followers_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_tracker_logs add constraint hrm_tracker_logs_tracker_flow_id_fkey FOREIGN KEY (tracker_flow_id) REFERENCES hrm_tracker_flow(id) ON DELETE CASCADE;
alter table public.hrm_tracker_logs add constraint hrm_tracker_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.hrm_users add constraint hrm_users_district_id_fkey FOREIGN KEY (district_id) REFERENCES hrm_districts(id) ON DELETE SET NULL;
alter table public.hrm_users add constraint hrm_users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.hrm_users add constraint hrm_users_item_id_fkey FOREIGN KEY (item_id) REFERENCES hrm_items(id) ON DELETE SET NULL;
alter table public.hrm_users add constraint hrm_users_office_id_fkey FOREIGN KEY (office_id) REFERENCES hrm_offices(id) ON DELETE SET NULL;
alter table public.hrm_users add constraint hrm_users_position_id_fkey FOREIGN KEY (position_id) REFERENCES hrm_positions(id) ON DELETE SET NULL;
alter table public.hrm_users add constraint hrm_users_salary_id_fkey FOREIGN KEY (salary_id) REFERENCES hrm_salaries(id) ON DELETE SET NULL;
alter table public.hrm_users add constraint hrm_users_school_id_fkey FOREIGN KEY (school_id) REFERENCES hrm_schools(id) ON DELETE SET NULL;
alter table public.ipcrfs add constraint ipcrfs_ipcrf_template_id_fkey FOREIGN KEY (ipcrf_template_id) REFERENCES ipcrf_templates(id) ON DELETE CASCADE;
alter table public.ipcrfs add constraint ipcrfs_rater_user_id_fkey FOREIGN KEY (rater_user_id) REFERENCES users(id) ON DELETE SET NULL;
alter table public.ipcrfs add constraint ipcrfs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
alter table public.kra_objectives add constraint kra_objectives_kra_id_fkey FOREIGN KEY (kra_id) REFERENCES kra(id) ON DELETE CASCADE;
alter table public.pms_competency_items add constraint pms_competency_items_compentency_id_fkey FOREIGN KEY (competency_id) REFERENCES pms_competencies(id) ON DELETE CASCADE;
alter table public.pms_idp add constraint fk_idp_ipcrf FOREIGN KEY (ipcrf_id) REFERENCES pms_ipcrf(id) ON DELETE CASCADE;
alter table public.pms_idp add constraint pms_idp_competency_item_id_fkey FOREIGN KEY (competency_item_id) REFERENCES pms_competency_items(id);
alter table public.pms_idp add constraint pms_idp_objective_id_fkey FOREIGN KEY (objective_id) REFERENCES pms_objectives(id);
alter table public.pms_ipcrf add constraint pms_ipcrf_ipcrf_template_id_fkey FOREIGN KEY (ipcrf_template_id) REFERENCES pms_ipcrf_templates(id);
alter table public.pms_ipcrf add constraint pms_ipcrf_rater_id_fkey FOREIGN KEY (rater_id) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.pms_ipcrf add constraint pms_ipcrf_user_id_fkey FOREIGN KEY (user_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.pms_ipcrf_competency_ratings add constraint fk_comp_rating_ipcrf FOREIGN KEY (ipcrf_id) REFERENCES pms_ipcrf(id) ON DELETE CASCADE;
alter table public.pms_ipcrf_competency_ratings add constraint fk_comp_rating_item FOREIGN KEY (competency_item_id) REFERENCES pms_competency_items(id) ON DELETE CASCADE;
alter table public.pms_ipcrf_objective_ratings add constraint fk_objective_rating_ipcrf FOREIGN KEY (ipcrf_id) REFERENCES pms_ipcrf(id) ON DELETE CASCADE;
alter table public.pms_ipcrf_objective_ratings add constraint fk_objective_rating_template_obj FOREIGN KEY (template_objective_id) REFERENCES pms_ipcrf_template_objectives(id) ON DELETE CASCADE;
alter table public.pms_ipcrf_positions add constraint pms_ipcrf_positions_ipcrf_template_id_fkey FOREIGN KEY (ipcrf_template_id) REFERENCES pms_ipcrf_templates(id) ON DELETE CASCADE;
alter table public.pms_ipcrf_positions add constraint pms_ipcrf_positions_position_id_fkey FOREIGN KEY (position_id) REFERENCES hrm_positions(id) ON DELETE CASCADE;
alter table public.pms_ipcrf_template_competencies add constraint ipcrf_template_competencies_competency_id_fkey FOREIGN KEY (competency_id) REFERENCES pms_competencies(id);
alter table public.pms_ipcrf_template_competencies add constraint pms_ipcrf_template_competencies_ipcrf_template_id_fkey FOREIGN KEY (ipcrf_template_id) REFERENCES pms_ipcrf_templates(id) ON DELETE CASCADE;
alter table public.pms_ipcrf_template_objectives add constraint pms_ipcrf_template_objectives_ipcrf_template_id_fkey FOREIGN KEY (ipcrf_template_id) REFERENCES pms_ipcrf_templates(id) ON DELETE CASCADE;
alter table public.pms_ipcrf_template_objectives add constraint pms_ipcrf_template_objectives_objective_id_fkey FOREIGN KEY (objective_id) REFERENCES pms_objectives(id) ON DELETE CASCADE;
alter table public.pms_ipcrf_templates add constraint pms_ipcrf_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES hrm_users(id) ON DELETE SET NULL;
alter table public.pms_objectives add constraint pms_objectives_kra_id_fkey FOREIGN KEY (kra_id) REFERENCES pms_kras(id);
alter table public.rr_candidates add constraint rr_candidates_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.rr_candidates add constraint rr_candidates_ranking_id_fkey FOREIGN KEY (ranking_id) REFERENCES rr_rankings(id) ON DELETE CASCADE;
alter table public.rr_criteria add constraint rr_criteria_ranking_id_fkey FOREIGN KEY (ranking_id) REFERENCES rr_rankings(id) ON DELETE CASCADE;
alter table public.rr_raters add constraint rr_raters_ranking_id_fkey FOREIGN KEY (ranking_id) REFERENCES rr_rankings(id) ON DELETE CASCADE;
alter table public.rr_raters add constraint rr_raters_user_id_fkey FOREIGN KEY (rater_id) REFERENCES hrm_users(id) ON DELETE CASCADE;
alter table public.rr_ratings add constraint rr_ratings_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES rr_candidates(id) ON DELETE CASCADE;
alter table public.rr_ratings add constraint rr_ratings_criterion_id_fkey FOREIGN KEY (criterion_id) REFERENCES rr_criteria(id) ON DELETE CASCADE;
alter table public.rr_ratings add constraint rr_ratings_ranking_id_fkey FOREIGN KEY (ranking_id) REFERENCES rr_rankings(id) ON DELETE CASCADE;
alter table public.rr_ratings add constraint rr_ratings_rater_id_fkey FOREIGN KEY (rater_id) REFERENCES rr_raters(id) ON DELETE CASCADE;
alter table public.users add constraint users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.users add constraint users_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;

-- NOTE: hrm_promotions.hrm_promotions_item_id_fkey pointed at stale table hrm_items_ in the old DB; re-pointed to hrm_items.

-- ====================== Unique / check constraints ======================

alter table public.hrm_leave_credits add constraint hrm_leave_credits_user_type_unique UNIQUE (user_id, type);
alter table public.hrm_medical_officer_schools add constraint hrm_medical_officer_schools_medical_officer_id_school_id_key UNIQUE (medical_officer_id, school_id);
alter table public.hrm_medical_officers add constraint hrm_medical_officers_org_id_user_id_key UNIQUE (org_id, user_id);
alter table public.hrm_ranking_applicant_points add constraint unique_committee_applicant UNIQUE (committee_criteria_id, applicant_id);
alter table public.pms_ipcrf_competency_ratings add constraint unique_competency_rating UNIQUE (ipcrf_id, competency_item_id, rater_type, period);
alter table public.pms_ipcrf_objective_ratings add constraint unique_objective_rating UNIQUE (ipcrf_id, template_objective_id, rater_type, period);
alter table public.rr_candidates add constraint rr_candidates_ranking_id_employee_id_key UNIQUE (ranking_id, employee_id);
alter table public.rr_criteria add constraint rr_criteria_weight_check CHECK ((weight > 0));
alter table public.rr_raters add constraint rr_raters_rater_id_ranking_id_key UNIQUE (rater_id, ranking_id);
alter table public.rr_ratings add constraint rr_ratings_points_check CHECK ((points >= 0));
alter table public.rr_ratings add constraint rr_ratings_rater_id_ranking_id_candidate_id_criterion_id_key UNIQUE (rater_id, ranking_id, candidate_id, criterion_id);
alter table public.users add constraint profiles_email_key UNIQUE (email);

-- ============================== Indexes ==============================

CREATE INDEX idx_ape_org ON public.hrm_annual_physical_exams USING btree (org_id);
CREATE INDEX idx_ape_user ON public.hrm_annual_physical_exams USING btree (hrm_user_id);
CREATE INDEX idx_ape_diagnoses_ape ON public.hrm_ape_diagnoses USING btree (ape_id);
CREATE INDEX idx_ape_diagnoses_org ON public.hrm_ape_diagnoses USING btree (org_id);
CREATE INDEX idx_hrm_items_removed_item_id ON public.hrm_items_removed USING btree (item_id);
CREATE INDEX idx_hrm_items_removed_org_id ON public.hrm_items_removed USING btree (org_id);
CREATE INDEX idx_hrm_items_removed_removed_at ON public.hrm_items_removed USING btree (removed_at DESC);
CREATE INDEX idx_hrm_items_removed_user_id ON public.hrm_items_removed USING btree (user_id);
CREATE INDEX idx_mo_schools_officer ON public.hrm_medical_officer_schools USING btree (medical_officer_id);
CREATE INDEX idx_mo_schools_school ON public.hrm_medical_officer_schools USING btree (school_id);
CREATE INDEX idx_medical_officers_org ON public.hrm_medical_officers USING btree (org_id);
CREATE INDEX idx_medical_officers_user ON public.hrm_medical_officers USING btree (user_id);
CREATE INDEX hrm_users_fts ON public.hrm_users USING gin (fts);
CREATE INDEX idx_users_firstname ON public.users USING btree (firstname);
CREATE INDEX idx_users_lastname ON public.users USING btree (lastname);
CREATE INDEX idx_users_middlename ON public.users USING btree (middlename);

-- ========================= Row level security =========================

alter table public.chiefs_opcrf enable row level security;
alter table public.competencies enable row level security;
alter table public.competency_items enable row level security;
alter table public.error_logs enable row level security;
alter table public.hrm_announcements enable row level security;
alter table public.hrm_annual_physical_exams enable row level security;
alter table public.hrm_ape_diagnoses enable row level security;
alter table public.hrm_assignments enable row level security;
alter table public.hrm_coordinatorships enable row level security;
alter table public.hrm_cto_users enable row level security;
alter table public.hrm_ctos enable row level security;
alter table public.hrm_designations enable row level security;
alter table public.hrm_development_plans enable row level security;
alter table public.hrm_districts enable row level security;
alter table public.hrm_erf_applicants enable row level security;
alter table public.hrm_global_remarks enable row level security;
alter table public.hrm_implementing_units enable row level security;
alter table public.hrm_interventions enable row level security;
alter table public.hrm_items enable row level security;
alter table public.hrm_items_removed enable row level security;
alter table public.hrm_leave_cards enable row level security;
alter table public.hrm_leave_coc enable row level security;
alter table public.hrm_leave_credits enable row level security;
alter table public.hrm_leave_dates enable row level security;
alter table public.hrm_majors enable row level security;
alter table public.hrm_medical_officer_schools enable row level security;
alter table public.hrm_medical_officers enable row level security;
alter table public.hrm_nosa enable row level security;
alter table public.hrm_nosi enable row level security;
alter table public.hrm_notifications enable row level security;
alter table public.hrm_offices enable row level security;
alter table public.hrm_pds enable row level security;
alter table public.hrm_personnel_coordinatorships enable row level security;
alter table public.hrm_personnel_grade_levels enable row level security;
alter table public.hrm_personnel_majors enable row level security;
alter table public.hrm_personnel_subjects enable row level security;
alter table public.hrm_position_qualifications enable row level security;
alter table public.hrm_positions enable row level security;
alter table public.hrm_promotions enable row level security;
alter table public.hrm_ranking_applicant_documents enable row level security;
alter table public.hrm_ranking_applicant_flow enable row level security;
alter table public.hrm_ranking_applicant_ier enable row level security;
alter table public.hrm_ranking_applicant_points enable row level security;
alter table public.hrm_ranking_applicants enable row level security;
alter table public.hrm_ranking_committee_criterias enable row level security;
alter table public.hrm_ranking_committees enable row level security;
alter table public.hrm_ranking_criterias enable row level security;
alter table public.hrm_ranking_evaluators enable row level security;
alter table public.hrm_ranking_expenses_summary enable row level security;
alter table public.hrm_ranking_qualifications enable row level security;
alter table public.hrm_rankings enable row level security;
alter table public.hrm_registrations enable row level security;
alter table public.hrm_remarks enable row level security;
alter table public.hrm_remarks_comments enable row level security;
alter table public.hrm_request_tracker_stickies enable row level security;
alter table public.hrm_request_trackers enable row level security;
alter table public.hrm_salaries enable row level security;
alter table public.hrm_school_years enable row level security;
alter table public.hrm_schools enable row level security;
alter table public.hrm_service_credit_users enable row level security;
alter table public.hrm_service_credits enable row level security;
alter table public.hrm_service_records enable row level security;
alter table public.hrm_subjects enable row level security;
alter table public.hrm_system_access enable row level security;
alter table public.hrm_tracker_flow enable row level security;
alter table public.hrm_tracker_followers enable row level security;
alter table public.hrm_tracker_logs enable row level security;
alter table public.hrm_users enable row level security;
alter table public.ipcrf_templates enable row level security;
alter table public.ipcrfs enable row level security;
alter table public.kra enable row level security;
alter table public.kra_objectives enable row level security;
alter table public.organizations enable row level security;
alter table public.pms_competencies enable row level security;
alter table public.pms_competency_items enable row level security;
alter table public.pms_idp enable row level security;
alter table public.pms_ipcrf enable row level security;
alter table public.pms_ipcrf_competency_ratings enable row level security;
alter table public.pms_ipcrf_objective_ratings enable row level security;
alter table public.pms_ipcrf_positions enable row level security;
alter table public.pms_ipcrf_template_competencies enable row level security;
alter table public.pms_ipcrf_template_objectives enable row level security;
alter table public.pms_ipcrf_templates enable row level security;
alter table public.pms_kras enable row level security;
alter table public.pms_objectives enable row level security;
alter table public.rr_candidates enable row level security;
alter table public.rr_criteria enable row level security;
alter table public.rr_rankings enable row level security;
alter table public.rr_raters enable row level security;
alter table public.rr_ratings enable row level security;
alter table public.users enable row level security;

-- ============================== Policies ==============================

create policy "Logged In users only" on public.chiefs_opcrf
  as permissive for all to authenticated
  using (true);
create policy "Logged in Users Only" on public.competencies
  as permissive for all to authenticated
  using (true);
create policy "Logged In Users Only" on public.competency_items
  as permissive for all to authenticated
  using (true);
create policy "public" on public.error_logs
  as permissive for all to public
  using (true);
create policy "auth" on public.hrm_announcements
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_announcements
  as permissive for select to public
  using (true);
create policy "APE authenticated delete" on public.hrm_annual_physical_exams
  as permissive for delete to authenticated
  using (true);
create policy "APE authenticated insert" on public.hrm_annual_physical_exams
  as permissive for insert to authenticated
  with check (true);
create policy "APE authenticated select" on public.hrm_annual_physical_exams
  as permissive for select to authenticated
  using (true);
create policy "APE authenticated update" on public.hrm_annual_physical_exams
  as permissive for update to authenticated
  using (true)
  with check (true);
create policy "APE diagnoses authenticated all" on public.hrm_ape_diagnoses
  as permissive for all to authenticated
  using (true)
  with check (true);
create policy "auth all" on public.hrm_assignments
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.hrm_coordinatorships
  as permissive for all to authenticated
  using (true);
create policy "auth only" on public.hrm_cto_users
  as permissive for all to authenticated
  using (true);
create policy "auth all" on public.hrm_ctos
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_designations
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.hrm_development_plans
  as permissive for all to authenticated
  using (true);
create policy "auth only" on public.hrm_districts
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_districts
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_erf_applicants
  as permissive for all to authenticated
  using (true);
create policy "auth only" on public.hrm_global_remarks
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_implementing_units
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.hrm_interventions
  as permissive for all to authenticated
  using (true);
create policy "auth (all)" on public.hrm_items
  as permissive for all to authenticated
  using (true);
create policy "select (public)" on public.hrm_items
  as permissive for select to public
  using (true);
create policy "all auth" on public.hrm_items_removed
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_leave_cards
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_leave_coc
  as permissive for all to public
  using (true);
create policy "auth" on public.hrm_leave_credits
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_leave_dates
  as permissive for all to authenticated
  using (true);
create policy "select (public)" on public.hrm_majors
  as permissive for select to public
  using (true);
create policy "MO schools authenticated all" on public.hrm_medical_officer_schools
  as permissive for all to authenticated
  using (true)
  with check (true);
create policy "MO authenticated all" on public.hrm_medical_officers
  as permissive for all to authenticated
  using (true)
  with check (true);
create policy "auth" on public.hrm_nosa
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_nosi
  as permissive for all to authenticated
  using (true);
create policy "auth all" on public.hrm_notifications
  as permissive for all to authenticated
  using (true);
create policy "public insert" on public.hrm_notifications
  as permissive for insert to public
  with check (true);
create policy "auth only" on public.hrm_offices
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_offices
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_pds
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.hrm_personnel_coordinatorships
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.hrm_personnel_grade_levels
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.hrm_personnel_majors
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.hrm_personnel_subjects
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_position_qualifications
  as permissive for all to authenticated
  using (true);
create policy "auth only" on public.hrm_positions
  as permissive for all to authenticated
  using (true);
create policy "select public" on public.hrm_positions
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_promotions
  as permissive for all to authenticated
  using (true);
create policy "public" on public.hrm_ranking_applicant_documents
  as permissive for all to public
  using (true);
create policy "public select" on public.hrm_ranking_applicant_documents
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_ranking_applicant_flow
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_ranking_applicant_ier
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_ranking_applicant_ier
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_ranking_applicant_points
  as permissive for all to public
  using (true);
create policy "public select" on public.hrm_ranking_applicant_points
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_ranking_applicants
  as permissive for all to authenticated
  using (true);
create policy "public insert" on public.hrm_ranking_applicants
  as permissive for insert to public
  with check (true);
create policy "public select" on public.hrm_ranking_applicants
  as permissive for select to public
  using (true);
create policy "public select" on public.hrm_ranking_committee_criterias
  as permissive for select to public
  using (true);
create policy "true" on public.hrm_ranking_committee_criterias
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_ranking_committees
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_ranking_committees
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_ranking_criterias
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_ranking_criterias
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_ranking_evaluators
  as permissive for all to public
  using (true);
create policy "auth" on public.hrm_ranking_expenses_summary
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_ranking_qualifications
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_ranking_qualifications
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_rankings
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_rankings
  as permissive for select to public
  using (true);
create policy "auth delete" on public.hrm_registrations
  as permissive for delete to authenticated
  using (true);
create policy "auth update" on public.hrm_registrations
  as permissive for update to authenticated
  using (true);
create policy "public insert" on public.hrm_registrations
  as permissive for insert to public
  with check (true);
create policy "public select" on public.hrm_registrations
  as permissive for select to public
  using (true);
create policy "auth only" on public.hrm_remarks
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_remarks_comments
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_request_tracker_stickies
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_request_trackers
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_request_trackers
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_salaries
  as permissive for all to authenticated
  using (true);
create policy "all auth" on public.hrm_school_years
  as permissive for all to authenticated
  using (true);
create policy "auth only" on public.hrm_schools
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_schools
  as permissive for select to public
  using (true);
create policy "auth all" on public.hrm_service_credit_users
  as permissive for all to authenticated
  using (true);
create policy "auth all" on public.hrm_service_credits
  as permissive for all to authenticated
  using (true);
create policy "auth " on public.hrm_service_records
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.hrm_subjects
  as permissive for all to authenticated
  using (true);
create policy "auth only" on public.hrm_system_access
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_system_access
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_tracker_flow
  as permissive for all to authenticated
  using (true);
create policy "public select" on public.hrm_tracker_flow
  as permissive for select to public
  using (true);
create policy "auth" on public.hrm_tracker_followers
  as permissive for all to authenticated
  using (true);
create policy "auth" on public.hrm_tracker_logs
  as permissive for all to authenticated
  using (true);
create policy "auth delete" on public.hrm_users
  as permissive for delete to authenticated
  using (true);
create policy "auth update" on public.hrm_users
  as permissive for update to authenticated
  using (true);
create policy "public insert" on public.hrm_users
  as permissive for insert to public
  with check (true);
create policy "public select" on public.hrm_users
  as permissive for select to public
  using (true);
create policy "Logged In Users Only" on public.ipcrf_templates
  as permissive for all to authenticated
  using (true);
create policy "Logged In Users Only" on public.ipcrfs
  as permissive for all to authenticated
  using (true);
create policy "Logged in Users Only" on public.kra
  as permissive for all to authenticated
  using (true);
create policy "Logged in Users Only" on public.kra_objectives
  as permissive for all to authenticated
  using (true);
create policy "auth only" on public.organizations
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_competencies
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_competency_items
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_idp
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_ipcrf
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_ipcrf_competency_ratings
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_ipcrf_objective_ratings
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_ipcrf_positions
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_ipcrf_template_competencies
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_ipcrf_template_objectives
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_ipcrf_templates
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_kras
  as permissive for all to authenticated
  using (true);
create policy "all (auth)" on public.pms_objectives
  as permissive for all to authenticated
  using (true);
create policy "Allow all for authenticated users" on public.rr_candidates
  as permissive for all to authenticated
  using (true)
  with check (true);
create policy "Allow all for authenticated users" on public.rr_criteria
  as permissive for all to authenticated
  using (true)
  with check (true);
create policy "Allow all for authenticated users" on public.rr_rankings
  as permissive for all to authenticated
  using (true)
  with check (true);
create policy "Allow all for authenticated users" on public.rr_raters
  as permissive for all to authenticated
  using (true)
  with check (true);
create policy "Allow all for authenticated users" on public.rr_ratings
  as permissive for all to authenticated
  using (true)
  with check (true);
create policy "Logged in Users Only" on public.users
  as permissive for all to authenticated
  using (true);

-- ============================== Realtime ==============================
-- The app subscribes to postgres_changes on hrm_notifications.
alter publication supabase_realtime add table public.hrm_notifications;

-- ============================== Storage ==============================
-- Buckets used by the app ('hrm' for documents/attachments, 'hrm_documents',
-- and the public 'hrm_public'). Storage OBJECTS must be migrated separately.
insert into storage.buckets (id, name, public) values
  ('hrm', 'hrm', false),
  ('hrm_documents', 'hrm_documents', false),
  ('hrm_public', 'hrm_public', true)
on conflict (id) do nothing;
