-- Timestamps behind the Ranking Turnaround Time report (/rankingturnaroundtime).
--
-- The report measures how long each stage of a ranking took, from the posting
-- of the vacancy to the appointment. Only two of the nine stages could be
-- dated before this migration: the posting window (display_on_portal_from /
-- _until) and the closing (closed_at, migration 0013). Everything else was
-- recorded as a boolean flag or a status string with no time attached, so the
-- report had nothing to compute.
--
-- Each column below is stamped by the app at the moment the action happens.
-- All are nullable: rankings that ran before this migration keep NULLs, and
-- the report shows a dash for those stages until someone fills them in
-- through hrm_ranking_stage_dates.

-- Stage 4, 6, 8 -- the three portal postings, previously bare booleans.
ALTER TABLE hrm_rankings ADD COLUMN IF NOT EXISTS ier_posted_at timestamptz;
ALTER TABLE hrm_rankings ADD COLUMN IF NOT EXISTS ranklist_posted_at timestamptz;
ALTER TABLE hrm_rankings ADD COLUMN IF NOT EXISTS rqa_posted_at timestamptz;

-- Stage 3 and 9. evaluation_status and status were overwritten in place, so
-- neither the screening nor the appointment left a trace of when it happened.
ALTER TABLE hrm_ranking_applicants ADD COLUMN IF NOT EXISTS evaluated_at timestamptz;
ALTER TABLE hrm_ranking_applicants ADD COLUMN IF NOT EXISTS appointed_at timestamptz;

-- Stage 5. Committee members cast points by upsert, so created_at defaults on
-- the first cast and updated_at is set explicitly on every save: together they
-- bound the deliberation period.
ALTER TABLE hrm_ranking_applicant_points ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE hrm_ranking_applicant_points ADD COLUMN IF NOT EXISTS updated_at timestamptz;

-- Manual stage dates. The columns above only fill in going forward, and the
-- automatic dates are a proxy for the real-world event (the deliberation date
-- is when points were encoded, not when the committee met). This table lets HR
-- correct any stage, and complete rankings that finished before the stamping
-- existed. A row here always wins over the derived date.
--
-- One row per stage per ranking; stage_key matches STAGES in
-- utils/turnaroundTime.ts.
CREATE TABLE IF NOT EXISTS hrm_ranking_stage_dates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ranking_id bigint NOT NULL REFERENCES hrm_rankings(id) ON DELETE CASCADE,
  stage_key text NOT NULL,
  date_from date,
  date_to date,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- The report upserts on this pair.
CREATE UNIQUE INDEX IF NOT EXISTS hrm_ranking_stage_dates_ranking_stage_unique
  ON hrm_ranking_stage_dates (ranking_id, stage_key);

-- Row Level Security. Consistent with the rest of the app, access is enforced in the
-- application layer; at the DB layer any authenticated user may read/write.
ALTER TABLE public.hrm_ranking_stage_dates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Ranking stage dates authenticated all" ON public.hrm_ranking_stage_dates;
CREATE POLICY "Ranking stage dates authenticated all"
  ON public.hrm_ranking_stage_dates
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
