name: Trigger Leave Credits Increment

on:
  schedule:
    - cron: '0 18 * * *' # This will run the workflow every day at 6 PM UTC, which is 2 AM UTC+8

jobs:
  triggerIncrement:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Leave Credits Increment API
        env:
          API_URL: https://eprime.sortbrite.com/api/cronann
        run: |
          curl -X POST "$API_URL"
